name: GOOLak
version: ${project.version}
main: net.imprex.goolak.GOOLakPlugin
api-version: '1.16'
authors: [Imprex]
commands:
  goolak:
    description: GOOLak admin command
    usage: /<command> reload
    permission: goolak.admin
permissions:
  goolak.admin:
    default: op
