name: GOOLak
version: 1.0.0
main: net.akat.goolak.GOOLakPlugin
api-version: '1.21'
folia-supported: true
authors: [AkatSireev, 2FORWORD2]
softdepend: [packetevents]
commands:
  goolak:
    description: GOOLak admin command
    usage: /<command> reload
    permission: goolak.admin
permissions:
  goolak.admin:
    default: op
