name: AkatAntiCheat
version: ${project.version}
main: net.imprex.lightxray.LightXRayPlugin
api-version: '1.16'
authors: [Imprex]
commands:
  akatanticheat:
    description: AkatAntiCheat admin command
    usage: /<command> reload
    permission: akatanticheat.admin
permissions:
  akatanticheat.admin:
    default: op
